target := iphone:clang:latest:14.0

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = EriAutoDance

EriAutoDance_FILES = main.mm
EriAutoDance_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/library.mk
