    - name: Compile dynamic library (.dylib for iOS)
      run: |
        SDK_PATH=$(xcrun --sdk iphoneos --show-sdk-path)
        echo "Using iOS SDK: $SDK_PATH"

        for src in lua-5.4.6/src/*.c; do
          if [[ "$src" != *"lua.c"* && "$src" != *"luac.c"* ]]; then
            xcrun --sdk iphoneos clang -arch arm64 -isysroot $SDK_PATH -c "$src" -O2 '-Dl_system(x)=((void)(x),-1)'
          fi
        done

        # Thêm đường dẫn -I cho header và -L cho thư viện local của bạn
        xcrun --sdk iphoneos clang++ -dynamiclib -arch arm64 -isysroot $SDK_PATH \
          -std=c++17 -fobjc-arc \
          main.mm *.o \
          -I lua-5.4.6/src \
          -I include \
          -L . \
          -framework Foundation \
          -framework UIKit \
          -lsubstrate \
          -o libautodance.dylib
