name: Build dylib CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Lua source code
      run: |
        curl -R -O https://www.lua.org/ftp/lua-5.4.6.tar.gz
        tar zxf lua-5.4.6.tar.gz

    - name: Compile dynamic library (.dylib for iOS)
      run: |
        # Lấy đường dẫn iOS SDK trên máy ảo macOS
        SDK_PATH=$(xcrun --sdk iphoneos --show-sdk-path)
        echo "Using iOS SDK: $SDK_PATH"

        # 1. Biên dịch từng file C của Lua sang object file (.o) cho iOS arm64
        # Thêm -Dl_system='(void)(0),-1' để loại bỏ hàm system() bị iOS chặn
        for src in lua-5.4.6/src/*.c; do
          if [[ "$src" != *"lua.c"* && "$src" != *"luac.c"* ]]; then
            xcrun --sdk iphoneos clang -arch arm64 -isysroot $SDK_PATH -c "$src" -O2 -Dl_system='(void)(0),-1'
          fi
        done

        # 2. Biên dịch main.mm kết hợp với các object files của Lua thành dylib cho iOS
        xcrun --sdk iphoneos clang++ -dynamiclib -arch arm64 -isysroot $SDK_PATH \
          -std=c++17 -fobjc-arc \
          main.mm *.o \
          -I lua-5.4.6/src \
          -framework Foundation \
          -framework UIKit \
          -o libautodance.dylib

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: autodance-dylib
        path: libautodance.dylib
